---
google_fonts:
    dest:
        fonts : static/externals/google_fonts/fonts
        css   : static/externals/google_fonts/css
    fonts:
        'Poppins':
            variants:
                - 200
                - 200italic
                - regular
                - italic
                - 700
                - 700italic
            subsets:
                - latin
                - latin-ext
            formats:
                - woff2
                - woff
        'Inter Tight':
            variants:
                - 700
            subsets:
                - latin-ext
            formats:
                - ttf
    icons:
        types:
            - 'Material Icons'
            - 'Material Icons Outlined'
        formats:
            - woff2
            - woff
